name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask
  - distributed
  - pandas
  - pyarrow
  - grpcio
  - pandas-gbq
  - google-cloud-bigquery
  - google-cloud-bigquery-storage